### ISSUE TITLE
(Do not) suppress errors by default

### ISSUE THREAD

**Issue by emq** [stimulusjs/stimulus#236] opened 2019-04-01 11:10 UTC
Re-issued by @sstephenson's request. Related comment in https://github.com/stimulusjs/stimulus/pull/53

Summary:

Currently javascript errors are not being propagated by default. Custom error handler _console-warns_ about errors - it breaks default behavior of popular error catcher services like sentry that are relying on `window.onerror` function.

I don't think such behavior is developer friendly and expected for _outside_ (Basecamp) developers - may I ask what was the reasoning behind it? 🤔

**Comment by sstephenson** [comment] 2019-04-03 23:29
Thanks for opening the issue!

Stimulus calls your application’s code in a few different places:

* When a controller is created, Stimulus calls the controller’s constructor function and the `Controller#initialize()` method
* When an element with a `data-controller` annotation appears in the DOM, Stimulus calls `Controller#connect()`; when it disappears, `Controller#disconnect()`
* When an event is dispatched on an element with a matching `data-action` annotation, Stimulus calls the controller’s corresponding action method

In each case, these calls happen inside a `try ... catch` block. If they didn’t, an error in any controller constructor, lifecycle callback, or action method would halt JavaScript execution, leaving Stimulus in an indeterminate state and possibly preventing subsequent callbacks or action methods from being invoked.

Inside the `catch` block, these errors make their way to a single endpoint, the `Application#handleError()` method. By default, this method calls `console.error()` to display a nicely formatted message, in red, including the error message, backtrace, controller, identifier, event, and element:

<img width="1107" alt="Screen Shot 2019-04-03 at 6 14 47 PM" src="https://user-images.githubusercontent.com/2603/55519177-67bd5a80-563c-11e9-9a9c-d86486014d97.png">

So this may be a case of each of us having a different idea of what it means for a framework to be “developer friendly.” My opinion is that it is more friendly for the framework not to break when application code raises an exception.

I also think our error logging is better, and that it’s a mischaracterization to say errors are “suppressed” when they appear by default in the browser’s console.

I admit that documentation around the `handleError` hook may be lacking. I’d love to discuss how we can improve it.

It’s also quite possible there’s a solution I haven’t considered that would let us have the best of both worlds: framework resilience against application errors _and_ automatic compatibility with tools like Sentry. Again, I’d love to discuss this, if you have any ideas.

Until then, closing this issue since things are working as designed.

**Closed by sstephenson** 2019-04-03 23:29 UTC

**Comment by ghiculescu** [comment] 2020-12-22 17:25
@sstephenson I just stumbled across this after being stung by something similar in production.

In terms of docs, I have two ideas on how to make this more visible.

1. A new section in https://stimulus.hotwire.dev/handbook/installing that contains @javan 's code snippet from https://github.com/hotwired/stimulus/pull/53
2. A new reference page https://stimulus.hotwire.dev/reference

I tend to think option 1 is worth doing; option 2 feels a bit much.

> It’s also quite possible there’s a solution I haven’t considered that would let us have the best of both worlds: framework resilience against application errors and automatic compatibility with tools like Sentry.

Most tools I've seen set [`window.onerror`](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror). So you could change https://github.com/hotwired/stimulus/blob/master/packages/@stimulus/core/src/application.ts#L72 to something like this:

```js
  handleError(error: Error, message: string, detail: object) {
    this.logger.error(`%s\n\n%o\n\n%o`, message, error, detail)

    window.onerror && window.onerror(message, null, null, null, error)
  }
```

Happy to put together PRs for either/both of these changes, if you'd be open to them?
