### ISSUE TITLE
Embedded script tags prevent target detection

### ISSUE THREAD

**Issue by Aesthetikx** [stimulusjs/stimulus#97] opened 2018-02-07 18:09 UTC
First off, thanks for the great work so far, stimulus is a joy to use.

Not sure if this is a bug or simply a limitation of the browser (or my misunderstanding of mutation observers, or something).

As of stimulus 1.0.0, in my experience if you have a <script> tag within a DOM node marked with a data-controller attribute, the corresponding stimulus controller will find targets with data-target attributes up to the point in the DOM where the <script> tag appears, and then no further. This has actually happened to me twice as I have been using stimulus in places that already had 'sprinkles of jquery', so this may be something that users run into as they replace those parts of their app with stimulus. This likely also comes up if people are using things like cocoon which embed script tags near the form.

Understandably having tiny <script> tags lying around may not be best practice, and I have been able to move them to the end of the document or at least beyond the last data-target, or replace them with stimulus entirely.

Let me know if you cannot reproduce or want help, but I assume this may be a known limitation?

**Comment by javan** [comment] 2018-02-07 18:18
Can you share a complete snippet of HTML that illustrates the problem, please?

**Comment by Aesthetikx** [comment] 2018-02-07 18:29
@javan This should do it, sorry for the messy js
https://gist.github.com/Aesthetikx/e7b2438f9ed31e269489af9ef9235bc6

**Comment by javan** [comment] 2018-02-07 19:02
Confirmed! Looks like it happens when the controller is registered *before* the document is complete and there are still inline `<script>`s to process. Stimulus returns the same (two) elements as  `querySelectorAll` so it's not a bug with the Targets API:
```js
connect() {
  // Both log the same elements
  console.log(this.itemTargets)
  console.log(this.element.querySelectorAll("[data-target='hello.item']"))
}
```
That said, I think Stimulus can probably help avoid this timing issue. In the meantime, you can avoid this by either:
1. Moving your Stimulus setup `<script>` to the end of the document before `</body>`
1. Moving it into a `.js` file loaded with `<script defer>` or `<script async>`
1. Registering controllers when the DOM is ready or even deferring briefly:
  ```js
  addEventListener("DOMContentLoaded", event => {
    application.register("hello", controller)
  })

  // Or:

  setTimeout(() => {
    application.register("hello", controller)
  }, 1)
  ```
Thanks for the report!

**Comment by david-a-wheeler** [comment] 2018-03-15 23:30
Clearly this should be documented. In real code, you really should put the script in a separate file and not inside the HTML in the first place.

**Closed** 2018-03-27 20:47 UTC

**Comment by Spone** [comment] 2018-07-10 17:10
I ran into this issue while using https://github.com/ankane/chartkick which outputs the javascript inline by default.

**Comment by jramiresbrito** [comment] 2020-06-11 19:14
I have a [bootstrap date time picker](https://eonasdan.github.io/bootstrap-datetimepicker/) being loaded in a modal. I'm trying to use stimulus to fetch any changes in one of my fields so I can update the second one. Basically they are start and finish hours, and the second must aways be in a range of 1 to 8 hours ahead the first.

I added the data-controller in my wrapper div and in my fields i added the data-target as follows:

`<%= f.input :hour_start, required: true, as: :string, label: 'Hora de inicio', input_html: { class: 'form-control datetimepicker' }, data: { target: "dtpicker.hour_start" } %>`

`<%= f.input :hour_finish, required: true, as: :string, label: 'Hora de termino', input_html: { class: 'form-control datetimepicker'}, data: { target: "dtpicker.hour_finish" } %>`

But when the page loads it raise:

```
application.js:106 Error connecting controller

Error: Missing target element "dtpicker.hour_start"
```

What I'm missing?
