### ISSUE TITLE
Issue using Stimulus with Sentry?

### ISSUE THREAD

**Issue by swanson** [stimulusjs/stimulus#252] opened 2019-05-28 14:34 UTC
:wave:

@javan we're seeing the same issue in Sentry: https://github.com/getsentry/sentry-javascript/issues/2074 using a stock Rails/Turbolinks/Stimulus setup

I think ultimately Sentry should not be breaking but is this a case where it is highlighting some issue with addEventListener in Stimulus? The root cause seems to be hitting the Chrome limit for event listeners but looks like the repro cases are in the thousands before it breaks. Could there be some kind of 'leak' where listeners are not being removed and accumulating over times in a Turbolinks environment?

**Comment by javan** [comment] 2019-05-28 14:57
The root cause is a Chrome bug (https://bugs.chromium.org/p/chromium/issues/detail?id=964249 → https://bugs.chromium.org/p/chromium/issues/detail?id=961199), not an event listener limit. The same issue occurs when event listeners are removed, which Stimulus and Turbolinks both correctly do. 

So, there's no leak, and nothing we can do on our end. Hopefully Sentry will come up with a workaround, and if not it'll be fixed in the next Chrome release.

**Closed by javan** 2019-05-28 14:57 UTC
