### ISSUE TITLE
Turbolinks, Stimulus, dynamic import(file.js) issue a blink, reloads div

### ISSUE THREAD

**Issue by frederikhors** [stimulusjs/stimulus#278] opened 2019-09-21 06:59 UTC
### REPRODUCTION: https://glitch.com/edit/#!/salty-savory

I'm using Stimulus with Turbolinks and I need to dynamic import many js in controllers.

The code I'm using in `main.js` is:

```js
window.Turbolinks.start()

window.application = window.Stimulus.Application.start()

const IsPreviewPage = () => document.documentElement.hasAttribute('data-turbolinks-preview')

const divID = 'about_graphic'

window.application.register("about", class extends window.Stimulus.Controller {
  async initialize () {
    console.log("About, initialize()")
        
    if (IsPreviewPage()) {
      return
    }  

    const about = await import("./about.js")
    about.WriteInDiv()
  }
})

```

### THE PROBLEM

If I navigate to `/about` the first time the `Date.now()` appears.

Then I navigate to `/index`.

When I come back on the `/about` page the `Date.now()` reloads itself (you can see a blink after the preview page issued by Turbolinks).

**How can I avoid the div reload?**

In this one, I'm not using dynamic import and it doesn't reload: https://glitch.com/edit/#!/quintessential-reptile

# >>> **UPDATE**

It blinks (reloads div) just if I use:

```js
async initialize () {
  console.log("About, initialize()")
        
  if (IsPreviewPage()) {
    return
  }  

  await import("./about.js")
  WriteInDiv()
}

const WriteInDiv() = () => {...}
```

# Why?

**Comment by javan** [comment] 2019-09-23 13:26
Duplicate of https://github.com/turbolinks/turbolinks/issues/492

**Closed by javan** 2019-09-23 13:26 UTC

**Comment by frederikhors** [comment] 2019-09-23 18:48
@javan do you have any hint about the problem? Anything for code organisation?
