### ISSUE TITLE
Super expression must either be null or a function

### ISSUE THREAD

**Issue by jwoertink** [stimulusjs/stimulus#280] opened 2019-10-07 19:33 UTC
I'm not sure what this error means, but my babel just updated, and now stimulus throws this error.

```javascript
import { Application } from "stimulus"
import EmailSignupController from "./controllers/email_signup_controller"

const application = Application.start()
// the offending line. Commenting this out stops the error.
application.register("email_signup", EmailSignupController)
```

I'm using `"stimulus": "^1.1.1"` and `"@babel/core": "7.6.2"`. When I was on babel 7.5.5 things worked fine.

**Comment by javan** [comment] 2019-10-07 19:57
Can you share a working example that reproduces the issue? I tried using Babel 7.6.2 and the same registration code without error:
- https://glitch.com/edit/#!/tundra-sneeze?path=src/index.js:3:0
- https://tundra-sneeze.glitch.me/

**Comment by jwoertink** [comment] 2019-10-07 20:10
When I try to update on that site, I get an error: 😒 

<img width="566" alt="Screen Shot 2019-10-07 at 12 59 32 PM" src="https://user-images.githubusercontent.com/2391/66344316-5d895b00-e902-11e9-8771-7b2dbc8ddd05.png">

My `EmailSignupController` is really simple:

```javascript
import { Controller } from 'stimulus'

export default class extends Controller {
  static get targets() {
    return [ 'email', 'agree', 'form', 'complete' ]
  }

  submit() {
    let errors = [];
    if(this.emailTarget.value === '') {
      errors.push("An email address is required")
    }
    if(!this.agreeTarget.checked) {
      errors.push("Please check the agree box.")
    }
    if(errors.length > 0) {
      errors.forEach(err => document.querySelector(".signup-form .errors").innerHTML += `<p>${err}</p>`)
    } else {
      this.completeTarget.style.display = "block"
      this.formTarget.style.display = "none"
    }
  }
}
```

As per normal JS stuff, my yarn.lock is pretty massive, so it's possible it's not a babel core issue, but maybe one of the other side deps. Here's the deps from my package.json

```
"devDependencies": {
    "@babel/core": "7.6.2",
    "@babel/plugin-proposal-class-properties": "7.5.5",
    "@babel/preset-env": "7.6.2",
    "@fortawesome/fontawesome-free": "5.10.1",
    "babel-loader": "8.0.6",
    "bootstrap": "4.3.1",
    "browser-sync": "2.26.7",
    "del": "5.0.0",
    "gulp": "4.0.2",
    "gulp-concat": "2.6.1",
    "gulp-imagemin": "^6.1.0",
    "gulp-newer": "^1.4.0",
    "gulp-noop": "^1.0.0",
    "gulp-rev": "^9.0.0",
    "gulp-sass": "^4.0.2",
    "gulp-size": "^3.0.0",
    "gulp-sourcemaps": "^2.6.5",
    "gulp-uglify": "^3.0.2",
    "jquery": "3.3.1",
    "normalize-scss": "^7.0.1",
    "photoswipe": "^4.1.3",
    "plyr": "^3.5.6",
    "popper.js": "1.15.0",
    "rails-ujs": "^5.2.3"
    "rev-del": "^2.0.0",
    "stimulus": "^1.1.1",
    "webpack-stream": "^5.2.1"
  }
```

**Comment by javan** [comment] 2019-10-07 20:20
Hmm, well, I can't reproduce using your controller code and dependency list. Does it work if you `rm yarn.lock && yarn install`? Does the stack track from the error point to anything?

**Comment by jwoertink** [comment] 2019-10-07 20:23
I tried blowing everything out, and I still get it. Unfortunately, the error isn't helpful. It says the error is on line 1 of bundle.js 😝  It doesn't show anything else. I'm using Firefox 69 on macOS 10.14.6 if that matters. I'll have to see what error I get in other browsers, or if it's just my machine being wonky.

**Comment by javan** [comment] 2019-10-07 20:24
Happy to try if you can share an example repo (or .zip of one).

**Comment by jwoertink** [comment] 2019-10-07 20:33
I appreciate the help. I wish I could share more of the code, but it's all work stuff 😞  I'll try it again and see if I can create a mini example somehow

**Comment by javan** [comment] 2019-10-07 20:34
> Unfortunately, the error isn't helpful. It says the error is on line 1 of bundle.js

Try turning off minification / production mode / etc.

**Comment by javan** [comment] 2019-10-11 14:24
Closing for now. Will reopen if you can trace this back to Stimulus. ✌️

**Closed by javan** 2019-10-11 14:24 UTC

**Comment by jwoertink** [comment] 2019-10-18 21:26
Good news, looks like it's not Stimulus. It seems to be uglify. Removing that solves the issue. The weird thing though was that I was using uglify before stimulus, and things worked fine. So some how a mix of having the two? But specifically related on the uglify side it seems. 

Anyway. Thanks for the help!
